site_name: 누리온 지침처
site_url: https://docs-admin.github.io/nurion-guide/

theme:
  name: material
  custom_dir: kisti-theme
  logo: assets/images/logo.png
  features:
    - navigation.expand
    - navigation.path    # (선택) 현재 위치를 상단에 표시
    # - navigation.indexes # (선택) 폴더 클릭 시 index.md로 바로 이동
  font:
    text: Noto Sans KR  # 본문: 구글 본고딕 (가장 깔끔함)
    code: Nanum Gothic Coding
    
# watch:
#   - mkdocs.yml
#   - docs

extra_javascript: []

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-pages

nav:
  - Home: README.md
  - System:
    - 시스템 개요 및 구성 : system/neuron-system-overview-and-configuration.md
    - 사용자 환경: system/user-environment.md
    - 사용자 프로그래밍 환경: system/user-programming-environment.md
    - 스케줄러(SLURM)를 통한 작업 실행: system/running-jobs-through-scheduler-slurm.md
    - 사용자 지원: system/user-support.md
  - Software:
    - 가우시안16(Gaussian16) on GPU: software/gaussian16-gpu-sw-userguide.md
  - Appendix:
    - 작업 스크립트 주요 키워드: appendix/appendix-1-main-keywords-for-job-scripts.md
    - Conda: appendix/appendix-2-how-to-use-conda.md
    - Singularity 컨테이너: appendix/appendix-3-how-to-use-singularity-container.md
    - Lustre striping: appendix/appendix-4-how-to-use-lustre-striping.md
    - 뉴론 Jupyter: appendix/appendix-5-neuron-jupyter-user-guideline.md
    - Keras 기반 Multi GPU 사용법: appendix/appendix-6-how-to-use-keras-based-multi-gpu.md
    - Conda 기반 Horovod 설치 방법: appendix/appendix-7-conda-environment-based-horovod-tensorflow-installation-method.md
    - 딥러닝 프레임워크 병렬화 (Horovod): appendix/appendix-8-how-to-use-deep-learning-framework-parallelization-horovod.md
    - AI 멀티노드 활용: appendix/ai.md
    - SSH Port Forwarding 을 통한 Jupyter 작업 실행: appendix/ssh-port-forwarding-jupyter.md
    - NVIDIA GPU Profiling: appendix/nvidia-gpu-profiling.md
    - 컨테이너 활용 가이드(작성 중 초안): appendix/undefined.md

markdown_extensions:
  - md_in_html
  - meta
  - attr_list
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic  
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false  
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets