site_name: 누리온 지침처
site_url: https://docs-admin.github.io/nurion-guide/

use_directory_urls: false

theme:
  name: material
  custom_dir: kisti-theme
  logo: assets/images/logo.png
  features:
    - navigation.sections # Groups items into collapsible sections
    - navigation.expand
    - navigation.path    # (선택) 현재 위치를 상단에 표시       
    # - navigation.indexes # (선택) 폴더 클릭 시 index.md로 바로 이동
  font:
    text: Noto Sans KR  # 본문: 구글 본고딕 (가장 깔끔함)
    code: Nanum Gothic Coding

extra_javascript: []

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-pages

nav:
  # - Home: README.md
  - System:
    - 시스템 개요 및 구성: system/nurion-system-overview-and-configuration.md
    - 사용자 환경: system/user-experience.md
    - 사용자 프로그래밍 환경: system/user-programming-environment.md
    - 스케줄러(PBS)를 통한 작업 실행: system/running-jobs-through-scheduler-pbs.md
    - 사용자 지원: system/user-support.md

  - Software:
    - ANSYS FLUENT: software/ansys-fluent.md
    - ANSYS CFX: software/ansys-cfx.md
    - Abaqus (2023 버전 이전): software/abaqus-2023.md
    - Abaqus (2024 버전 이후): software/abaqus-2024.md
    - NASTRAN: software/nastran-userguide.md
    - 가우시안16(Gaussian16) LINDA: software/gaussian16-linda-userguide.md
    - 가우시안16(Gaussian16): software/gaussian16-userguide.md

  - Appendix:
    - 작업 스크립트 주요 키워드: appendix/appendix-1-main-keywords-for-job-scripts.md
    - Conda: appendix/appendix-2-how-to-use-conda.md
    - Singularity 컨테이너: appendix/appendix-3-how-to-use-singularity-container.md
    - Lustre stripe: appendix/appendix-4-how-to-use-lustre-striping.md
    - 데이터 아카이빙: appendix/appendix-5-tsmsf-user-guidelines.md
    - MVAPICH2 성능 최적화 옵션: appendix/appendix-6-method-for-using-the-mvapich2-performance-optimization-option.md
    - 딥러닝 프레임워크 병렬화: appendix/appendix-7-method-for-using-deep-learning-framework-parallelization.md
    - 공통라이브러리 목록: appendix/appendix-8-list-of-common-libraries.md
    - 데스크톱 가상화(VDI): appendix/appendix-9-how-to-use-vdi.md
    - 버스트버퍼(Burst Buffer) : appendix/appendix-10-how-to-use-burst-buffer.md
    - 플랫 노드(Flat node): appendix/appendix-11-how-to-use-flat-node.md
    - DTN(데이터전송노드): appendix/dtn.md

markdown_extensions:
  - md_in_html
  - meta
  - attr_list
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic  
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false  
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

extra:
  analytics:
    provider: google
    # property: G-G3T2F096SV # Main G-Tag
    property: G-BFN3CHFMDF # Data Stream 
